# Generated by Django 4.2.5 on 2023-09-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
