# Generated by Django 4.2.5 on 2023-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
