# Generated by Django 4.2.5 on 2023-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_review_profile_img_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='google_form_link',
            field=models.URLField(blank=True),
        ),
    ]
